name: Build TypeScript Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: List lib folder contents
        run: ls -R lib

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lib
          path: lib/
